# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tom Manderson
email: me@trm.io
description: > # this means to ignore newlines until "baseurl:"
  Consulting software engineer, software engineering/Mathematics student,
  Pythonista/Haskeller
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trm.io" # the base hostname & protocol for your site
twitter_username:  TRManderson
github_username:   TRManderson
linkedin_username: TRManderson

# Build settings
markdown: kramdown
google_analytics: UA-36521202-5
permalink: /:year/:month/:day/:title.html
comments: true
disqus:
  shortname: trm-io